version: 2
jobs:
  build:
    environment:
      DOCKER_IMAGE: tenstartups/nginx-proxy:latest
      DOCKERFILE: Dockerfile
    machine: true
    steps:
      - checkout
      - run: docker build --file ${DOCKERFILE} --tag ${DOCKER_IMAGE} .
      - run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      - run: docker push ${DOCKER_IMAGE}

workflows:
  version: 2
  build_all:
    jobs:
      - build
